apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: run-react-local
  title: Run React App Locally
  description: Clone, install, and launch a React app locally with a single action
spec:
  owner: dev-team
  type: tool

  parameters:
    - title: Git repository for the React app
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository URL
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
    - title: Local path to clone into
      required:
        - path
      properties:
        path:
          title: Clone path
          type: string
          description: Path on your local machine
    - title: Port to use (default: 3001)
      properties:
        port:
          title: Dev server port
          type: string
          default: "3001"

  steps:
    - id: clone
      name: Clone the React app
      action: fetch:plain
      input:
        url: ${{ parameters.repoUrl }}
        targetPath: ${{ parameters.path }}
    - id: install
      name: Install dependencies
      action: run:command
      input:
        command: 'npm install'
        workingDirectory: ${{ parameters.path }}
    - id: start
      name: Start development server
      action: run:command
      input:
        command: 'npm start -- --port ${{ parameters.port }}'
        workingDirectory: ${{ parameters.path }}

  output:
    links:
      - title: Open in browser
        url: "http://localhost:${{ parameters.port }}"